[DMTrack] # <tracker-name>
label = DMTrack
protocol = traxpython
command =  rgbd
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
paths = /data/2024/DMTrack/lib/test/vot
